### ISSUE TITLE
Doesn't compile with latest http-conduit 2.2.0

### ISSUE THREAD

**Issue by felixonmars** [aristidb/aws#206]
```
[ 3 of 76] Compiling Aws.Core         ( Aws/Core.hs, dist/build/Aws/Core.o )

Aws/Core.hs:497:9: error:
    Not in scope: `HTTP.checkStatus'
    Perhaps you meant `HTTP.mkStatus' (imported from Network.HTTP.Types)
    Neither `Network.HTTP.Types' nor `Network.HTTP.Conduit' exports `checkStatus'.
```

Related change:

snoyberg/http-client@b476183

**Comment by ilovezfs** [comment]
Any progress on this?

**Comment by aristidb** [comment]
I haven't had time to work on this yet, but Pull Requests are always
welcome.

ilovezfs <notifications@github.com> schrieb am Fr., 22. Juli 2016, 13:32:

**Comment by jkachmar** [comment]
I just poked at this a little bit and wanted to share what I found, since I don't have the time to go further right now:

* `instance Default Request` has been removed; `Network.HTTP.Client.defaultRequest` should be used instead of `Data.Default.def`
* `checkResponse` changed its type signature from `checkStatus`; the default response is now `\_ _ -> return ()`

Changing these lets `Aws.Core` compile, but causes `Aws.S3.Commands.GetObject` to fail wit the following messages

```
    Couldn't match expected type ‘HTTP.CookieJar -> r0’
                with actual type ‘HTTP.HttpExceptionContent’
    The function ‘HTTP.StatusCodeException’
    is applied to three arguments,
    but its type ‘HTTP.Response ()
                  -> B8.ByteString -> HTTP.HttpExceptionContent’
    has only two
    In the second argument of ‘($)’, namely
      ‘HTTP.StatusCodeException status headers cookies’
    In the expression:
      throwM $ HTTP.StatusCodeException status headers cookies
```

```
    Couldn't match expected type ‘HTTP.Response ()’
                with actual type ‘HTTP.Status’
    In the first argument of ‘HTTP.StatusCodeException’, namely
      ‘status’
    In the second argument of ‘($)’, namely
      ‘HTTP.StatusCodeException status headers cookies’
```

```
    Couldn't match type ‘[HTTP.Header]’ with ‘B8.ByteString’
    Expected type: B8.ByteString
      Actual type: HTTP.ResponseHeaders
    In the second argument of ‘HTTP.StatusCodeException’, namely
      ‘headers’
    In the second argument of ‘($)’, namely
      ‘HTTP.StatusCodeException status headers cookies’
```

Hopefully someone finds this helpful!

**Comment by bgamari** [comment]
@aristidb I think it would make sense to push out a release at this point; the restrictive bounds on `aws` are becoming quite painful.

**Comment by aristidb** [comment]
@bgamari Please feel free to go ahead and make the release. :-)

**Comment by aristidb** [comment]
I believe #213 closes this issue.

**Comment by bgamari** [comment]
Aristid Breitkreuz <notifications@github.com> writes:

> @bgamari Please feel free to go ahead and make the release. :-)
>
Will do. Thanks!
